version: '3.8'

services:
  ansiblecontainer:
    image: gustavmk/ansiblecontainer:latest
    volumes:
      - .:/work:rw
    working_dir: /work
    environment:
      - ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID}
      - ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET}
      - ARM_CLIENT_ID=${ARM_CLIENT_ID}
      - ARM_TENANT_ID=${ARM_TENANT_ID}
      - TF_IN_AUTOMATION=true